---
- name: 普通にloop
  hosts: all
  tasks:
    - debug:
        msg: "{{ item }}"
      loop: [0, 2, 4, 6, 8, 10]

- name: product filter
  hosts: all
  tasks:
    - debug:
        var: item
      loop: "{{ ['alice', 'bob'] | product(['client', 'employeedb', 'providerdb']) | list }}"

- name: loop_control label
  hosts: all
  tasks:
    - debug:
        msg: "{{ item.name }}"
      loop:
        - name: server1
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
      loop_control:
        label: "{{ item.name }}"
